"""Gemini CLI agent implementation."""

import json
from pathlib import Path

from llm_ide_rules.agents.base import (
    BaseAgent,
    get_ordered_files,
    resolve_header_from_stem,
    strip_toml_metadata,
    trim_content,
    extract_description_and_filter_content,
)


class GeminiAgent(BaseAgent):
    """Agent for Gemini CLI."""

    name = "gemini"
    rules_dir = None
    commands_dir = ".gemini/commands"
    rule_extension = None
    command_extension = ".toml"

    def bundle_rules(
        self, output_file: Path, section_globs: dict[str, str | None] | None = None
    ) -> bool:
        """Gemini CLI doesn't support rules, only commands."""
        return False

    def bundle_commands(
        self, output_file: Path, section_globs: dict[str, str | None] | None = None
    ) -> bool:
        """Bundle Gemini CLI command files (.toml) into a single output file."""
        commands_dir = self.commands_dir
        if not commands_dir:
            return False

        commands_path = output_file.parent / commands_dir
        if not commands_path.exists():
            return False

        extension = self.command_extension
        if not extension:
            return False

        command_files = list(commands_path.glob(f"*{extension}"))
        if not command_files:
            return False

        ordered_commands = get_ordered_files(
            command_files, list(section_globs.keys()) if section_globs else None
        )

        content_parts: list[str] = []
        for command_file in ordered_commands:
            content = command_file.read_text().strip()
            if not content:
                continue

            content = strip_toml_metadata(content)
            header = resolve_header_from_stem(
                command_file.stem, section_globs if section_globs else {}
            )
            content_parts.append(f"## {header}\n\n")
            content_parts.append(content)
            content_parts.append("\n\n")

        if not content_parts:
            return False

        self._write_bundled_content(output_file, "".join(content_parts))
        return True

    def write_rule(
        self,
        content_lines: list[str],
        filename: str,
        rules_dir: Path,
        glob_pattern: str | None = None,
        description: str | None = None,
    ) -> None:
        """Gemini CLI doesn't support rules."""
        pass

    def write_command(
        self,
        content_lines: list[str],
        filename: str,
        commands_dir: Path,
        section_name: str | None = None,
    ) -> None:
        """Write a Gemini CLI command file (.toml) with TOML format."""
        import tomli_w

        extension = self.command_extension or ".toml"
        filepath = commands_dir / f"{filename}{extension}"

        description, filtered_content = extract_description_and_filter_content(
            content_lines, ""
        )

        final_content = []
        found_header = False
        for line in filtered_content:
            if not found_header and line.startswith("## "):
                found_header = True
                continue
            final_content.append(line)

        final_content = trim_content(final_content)
        content_str = "".join(final_content).strip()

        desc = description if description else (section_name or filename)

        # Construct dict and dump to TOML
        data = {
            "description": desc,
            "prompt": content_str + "\n",  # Ensure trailing newline in multiline string
        }

        # tomli-w will handle escaping and multiline strings automatically
        output = tomli_w.dumps(data)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(output)

    def generate_root_doc(
        self,
        general_lines: list[str],
        rules_sections: dict[str, list[str]],
        command_sections: dict[str, list[str]],
        output_dir: Path,
        section_globs: dict[str, str | None] | None = None,
    ) -> None:
        """Gemini CLI uses AGENTS.md (generated by 'agents' agent). This is a no-op."""
        pass

    def configure_agents_md(self, base_dir: Path) -> bool:
        """Configure Gemini CLI to use AGENTS.md."""
        import json

        settings_path = base_dir / ".gemini" / "settings.json"
        settings_path.parent.mkdir(parents=True, exist_ok=True)

        data = {}
        if settings_path.exists():
            try:
                data = json.loads(settings_path.read_text())
            except Exception:
                pass

        old_data = json.dumps(data, sort_keys=True)
        
        if "context" not in data:
            data["context"] = {}

        file_names = data["context"].get("fileName", [])
        if isinstance(file_names, str):
            file_names = [file_names]

        if "AGENTS.md" not in file_names:
            file_names = ["AGENTS.md"] + [f for f in file_names if f != "AGENTS.md"]
            if "GEMINI.md" not in file_names:
                file_names.append("GEMINI.md")
            data["context"]["fileName"] = file_names

        new_data = json.dumps(data, sort_keys=True)
        if old_data == new_data and settings_path.exists():
            return False

        settings_path.write_text(json.dumps(data, indent=2))
        return True

    def check_gemini_config(self, base_dir: Path) -> bool:
        """Check if Gemini CLI is configured to use AGENTS.md (local or global)."""
        import os

        # Check local config
        local_settings = base_dir / ".gemini" / "settings.json"
        if self._check_gemini_config(local_settings):
            return True

        # Check global config
        global_settings = Path(os.path.expanduser("~/.gemini/settings.json"))
        return self._check_gemini_config(global_settings)

    def _check_gemini_config(self, config_path: Path) -> bool:
        """Check if a specific Gemini CLI config file is configured to use AGENTS.md."""
        import json

        if not config_path.exists():
            return False

        try:
            data = json.loads(config_path.read_text())
            file_names = data.get("context", {}).get("fileName", [])
            if isinstance(file_names, str):
                return file_names == "AGENTS.md"
            elif isinstance(file_names, list):
                return "AGENTS.md" in file_names
        except Exception:
            pass

        return False
